### ISSUE TITLE
Vortices module failing to create phase profile

### ISSUE THREAD

**Issue by wheelerMT** [wheelerMT/pygpe#5]
There is a problem in which the vortex_phase_profile function within the vortices module is mixing arrays defined on both the CPU and GPU.
For example, calling `vortex_phase_profile function(grid, 100, 1.0)` results in the traceback
```python
Attempting to find 100 positions...
Successfully found 100 positions in 100 iterations!
Traceback (most recent call last):
  File "c:\dev\python\pygpe\examples\scalar\2d_SQV_imprinting.py", line 18, in <module>
    phase = vortex_phase_profile(grid, 100, 1.0)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\python\pygpe\pygpe\shared\vortices.py", line 100, in vortex_phase_profile
    heaviside_x_plus = _heaviside(x_plus)
                       ^^^^^^^^^^^^^^^^^^
  File "C:\dev\python\pygpe\pygpe\shared\vortices.py", line 61, in _heaviside
    return np.where(array < 0, np.zeros(array.shape), np.ones(array.shape))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in where
  File "cupy\_core\core.pyx", line 1723, in cupy._core.core._ndarray_base.__array_function__
  File "C:\dev\python\pygpe\.venv\Lib\site-packages\cupy\_sorting\search.py", line 211, in where
    return _where_ufunc(condition.astype('?'), x, y)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy\_core\_kernel.pyx", line 1287, in cupy._core._kernel.ufunc.__call__
  File "cupy\_core\_kernel.pyx", line 160, in cupy._core._kernel._preprocess_args
  File "cupy\_core\_kernel.pyx", line 146, in cupy._core._kernel._preprocess_arg
TypeError: Unsupported type <class 'numpy.ndarray'>
``` 

The error lies within the module using NumPy functions mixed with the GPU arrays of the `Grid` class. I propose to just swap all NumPy functions within the vortices module over to CuPy versions.

**Comment by wheelerMT** [comment]
Fixed in #6
